"""autogen current models

Revision ID: e944015c1998
Revises: 0003_stamp_current
Create Date: 2025-08-22 17:07:42.467839
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'e944015c1998'
down_revision = '0003_stamp_current'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
